services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./blog_api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  bot:
    build:
      context: .
    container_name: telegram_bot
    command: python bot/main.py
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - db

volumes:
  postgres_data: